services:
  download:
    build: .
    image: sky-detector
    command: python src/dataset_downloader/dataset_downloader.py
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - ASTROMETRY_API_KEY=${ASTROMETRY_API_KEY}

  train:
    build: .
    image: sky-detector
    command: python -m src.model_training.train --dataset /app/data/dataset --output /app/data/trained-models --performance /app/data/performance
    user: root
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    runtime: nvidia
    environment:
      - ASTROMETRY_API_KEY=${ASTROMETRY_API_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/app/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  infer:
    build: .
    image: sky-detector
    command: >
      python -m src.model_applications.run_inference
      --model /app/data/trained-models/model-2026_03_08-17_21_19.pt
      --image /app/data/dataset/11000896/11000896-image.fits
      --output /app/data/performance/infer_result.png
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - ASTROMETRY_API_KEY=${ASTROMETRY_API_KEY}
      - PYTHONPATH=/app/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  eval:
    build: .
    image: sky-detector
    command: >
      python -m src.model_applications.run_evaluation
      --model /app/data/trained-models/model-2026_03_08-17_21_19.pt
      --dataset /app/data/dataset/
      --output /app/data/performance/eval-2026_03_08-17_21_19/
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - ASTROMETRY_API_KEY=${ASTROMETRY_API_KEY}
      - PYTHONPATH=/app/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]